### ISSUE TITLE
Can't resolve 'proptypes'

### ISSUE THREAD

**Issue by maliDzony** [axetroy/react-download#7]
Hey :) there is a problem with proptypes

```
in ./node_modules/@axetroy/react-download/lib/react-download.js
Module not found: Error: Can't resolve 'proptypes' in '/Users/Projects/storybook/node_modules/@axetroy/react-download/lib'
```

but if I change 
`require("proptypes"))` to `require("prop-types"));`
in /lib/reactDownload it works

I think it's more common to use "prop-types" lib then "proptypes"

btw, useful component!

**Comment by luanfonceca** [comment]
I am facing the same issue right now.

**Comment by axetroy** [comment]
I am sorry about this.

Fix this in the new version
